version: '3'
services:
  swagger:
    image: nginx:alpine
    ports:
      - 18080:80
    volumes:
      - type: bind
        source: "./swagger"
        target: "/usr/share/nginx/html"
    stdin_open: true
    tty: true
  # browser:
  #   image: ./
  #   ports:
  #     - 18081:8080
  #   volumes:
  #     - type: bind
  #       source: "./web"
  #       target: "/go/src/app"
  #   stdin_open: true
  #   tty: true
  api:
    image: golang:1.25-alpine
    ports:
      - 18082:8080
    volumes:
      - type: bind
        source: "./src"
        target: "/go/src/app"
    environment:
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      DB_TLS: "${DB_TLS}"
      # DB_CA_CERT: "${DB_CA_CERT}"
      # DB_CLIENT_CERT: "${DB_CLIENT_CERT}"
      # DB_CLIENT_KEY: "${DB_CLIENT_KEY}"
    stdin_open: true
    tty: true 
  