CREATE TABLE IF NOT EXISTS experiments (
    experiment_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(32) NOT NULL,
    description VARCHAR(512),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (experiment_id)
);

CREATE TABLE IF NOT EXISTS runs (
    run_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    experiment_id INT UNSIGNED NOT NULL,
    name VARCHAR(32),
    description VARCHAR(512),
    failure_reason VARCHAR(512),
    status TINYINT UNSIGNED NOT NULL DEFAULT 0,
    started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at DATETIME,
    PRIMARY KEY (run_id),
    FOREIGN KEY (experiment_id) REFERENCES experiments(experiment_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS parameters (
    parameter_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    run_id INT UNSIGNED NOT NULL,
    name VARCHAR(32) NOT NULL,
    value VARCHAR(32) NOT NULL,
    PRIMARY KEY (parameter_id),
    FOREIGN KEY (run_id) REFERENCES runs(run_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS metrics (
    metric_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    run_id INT UNSIGNED NOT NULL,
    name VARCHAR(32) NOT NULL,
    PRIMARY KEY (metric_id),
    FOREIGN KEY (run_id) REFERENCES runs(run_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS plots (
    metric_id INT UNSIGNED NOT NULL,
    step BIGINT UNSIGNED NOT NULL,
    value DOUBLE NOT NULL,
    PRIMARY KEY (metric_id, step),
    FOREIGN KEY (metric_id) REFERENCES metrics(metric_id) ON DELETE CASCADE
);